### ISSUE TITLE
Setting textContent doesn't escape the content

### ISSUE THREAD

**Issue by lamplightdev** [matthewp/ocean#24]
Hi Matthew,

I'm not sure if this is a bug in Ocean or linkedom (although linkedom does have a test case covering it https://github.com/WebReflection/linkedom/blob/11d016420780d60163a4c5719b48e303f0b48ae7/test/interface/text.js#L15), but when setting the `textContent` of an element the value gets passed through as is, with no escaping. I'd expect the following test to pass:

```js
Deno.test('textContent is escaped', async() => {
  let { html } = new Ocean({ document });
  class TextContentElement extends HTMLElement {
    constructor() {
      super();
      this.attachShadow({ mode: 'open' });
    }
    connectedCallback() {
      let el = document.createElement('div');
      el.textContent = '<strong>test</strong>';
      this.shadowRoot.append(el);
    }
  }
  customElements.define('text-content-el', TextContentElement);
  let iter = html`<div outer><text-content-el></text-content-el></div>`;
  let out = await consume(iter);
  assertStringIncludes(out, `<div>&lt;strong&gt;test&lt;/strong&gt;</div>`, 'shadow rendered'); 
});
```

but it fails, passing only with:

```js
assertStringIncludes(out, `<div><strong>test</strong></div>`, 'shadow rendered'); 
```

Thanks!
Chris.

**Comment by matthewp** [comment]
Oh, that's an interesting one. I can definitely see how you'd maybe expect/want that to be escaped. On the other hand, on a more practical level, Ocean doesn't touch interpolated values. In this particular example the first span is turned into DOM just for parsing (to find custom elements) and then turned back into a string. Without escaping (all) values (which is probably wanted) I'm not sure we could really do that.

Happy to discuss in a new issue though.
